version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: zilehuda
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      - db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_API_BASE_URL=http://backend:8000/api
  #   depends_on:
  #     - backend

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: zilehuda
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
